### ISSUE TITLE
Disappearing images in Google Chrome, mac os x

### ISSUE THREAD

**Issue by charlau** [bkosborne/jQuery-Waterwheel-Carousel#1]
I've been working on this bug the whole day. In Google Chrome, while the carousel is animating to its starting position, all but the center image disappear. Looking at the resulting html, they get an inline style of 'width:0'. It's intermittent, but happens a lot. I first thought that it was a preload problem. But I found this solution:

On line 262 of jquery.waterwheelCarousel-1.2.2.js (btw, version number is not updated in the js files), in the 'performCalculations' function, there's width & height calculations being made. However, just before (lines 252-259) there's a commented block doing the same thing but in a different way. 

Inverting the 2 blocks solved the problem.

**Comment by bkosborne** [comment]
Thanks for this!
