### ISSUE TITLE
Lazy loading images

### ISSUE THREAD

**Issue by thoronas** [bkosborne/jQuery-Waterwheel-Carousel#10]
Love this plugin. I want to use it for a large scale community photo album but the album could potentially have up to 2000 images. I'd like to store the images in an object and then load them in batches as people cycle through them. Not sure if this would possible with the api or not.

**Comment by bkosborne** [comment]
Hmm not at the moment, and it seems like a pretty big change. I'd almost have to write very specialized code for retrieving and parsing the new data. 

Have you found any other carousels that load new images dynamically?

**Comment by thoronas** [comment]
I know Elastislider (http://tympanus.net/codrops/2011/09/12/elastislide-responsive-carousel/) has a function for dynamically adding new images. However it's not doing the same visual styling your slider is doing. Like you said it would have to be a big change to add them into the slider. I was originally thinking I could use your reload api call while maintaining the current slide in center but then I'd just be reloading all the images which wouldn't work out. 

Thanks for the response.
